import java.util.Scanner;

public class ExceptionEx1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		
			
//			try {
//				resultNum = num / module;
//			} catch (ArithmeticException e) {
//				// TODO: handle exception
//				System.out.println("논리적인 오류가 발생해서 예외처리됨.");
//			} catch (ArrayIndexOutOfBoundsException e) {
//				// TODO: handle exception
//				System.out.println("배열 접근 오류가 발생해서 예외처리됨.");
//			}
//			
//			System.out.println("결과 값: " + resultNum);
			
		
	}

}
